In [1]:
import tensorflow as tf

### scalar data

In [2]:
s1 = 10
s2 = 'abc'
s3 = 3.14

### vector data

In [ ]:
v = [10,20,30] #shape (3,)

### matrix data

In [ ]:
m = [ [10,20,30], [10,20,30] ] #shape( 2,3)

### 3d 

In [ ]:
d3= [ [ [10,20,30], [10,20,30] ], [ [10,20,30], [10,20,30] ] ] #shape( 2, 2, 3)

### 4d

In [ ]:
d4 = [ [ [ [10,20,30], [10,20,30] ], [ [10,20,30], [10,20,30] ] ],
[ [ [10,20,30], [10,20,30] ], [ [10,20,30], [10,20,30] ] ] ] #shape( 2, 2, 2, 3)

### 텐서 데이터 노드를 정의 하는 방법
1. constant: 읽기전용
2. Variable: 읽기 쓰기

In [5]:
s1 = 10
c1 = tf.constant( s1 )
c1

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
c1.numpy()

10

In [7]:
v1 = [10,20,30]
t1 = tf.constant( v1 )
t1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30])>

In [8]:
type( t1 )

tensorflow.python.framework.ops.EagerTensor

In [9]:
t1.numpy()

array([10, 20, 30])

In [10]:
m1 = tf.constant( [[10,20,30],[40,50,60]] )
m1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]])>

### 산술연산 : 
1. element wise(요소별연산): 동일한 인덱스 끼리 연산
2. broad castring :자동확장( 연산대상 사이즈로)

In [11]:
a = tf.constant( 3 )
b = tf.constant( [1,2,3])

In [12]:
c = tf.multiply( a,b) # c= a*b
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

In [ ]:
[3,3,3] x [1,2,3]

In [13]:
c.numpy()

array([3, 6, 9])

In [19]:
f = tf.constant( [1,2,3] )
g = tf.constant( [ [1,2,3],[4,5,6],[7,8,9] ] )

In [20]:
h = tf.add( f,g ) # h = f+g

In [16]:
h.numpy()

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [21]:
i = tf.constant( [[1],[2],[3]] ) # 3x1
j = tf.constant( [ [1,2,3],[4,5,6],[7,8,9] ] )

In [22]:
k = i*j # tf.multiply( i,j)

In [23]:
k

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])>

### 행렬곱

In [24]:
o = tf.constant( [ [1,2],[3,4] ] ) # 행렬
p = tf.constant( [ [5,6],[7,8] ] ) #행렬
q = tf.multiply( o,p )
r = tf.matmul( o,p ) #  행렬곱

In [25]:
q.numpy()

array([[ 5, 12],
       [21, 32]])

In [26]:
r.numpy()

array([[19, 22],
       [43, 50]])

## 많이 사용하는 operation

In [27]:
s = [1,2,3]
t = tf.square( s ) # s**2
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [28]:
u = tf.reduce_mean( s )
u

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Variable

In [29]:
v = tf.Variable( 10 )
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [30]:
type(v)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [ ]:
# v.assign( 3 )
# v.assign_add( 3 )
v.assign_sub( 3 )