In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/cars.csv', index_col='Unnamed: 0')
df

speed  dist
1       4     2
2       4    10
3       7     4
4       7    22
5       8    16
6       9    10
7      10    18
8      10    26
9      10    34
10     11    17
11     11    28
12     12    14
13     12    20
14     12    24
15     12    28
16     13    26
17     13    34
18     13    34
19     13    46
20     14    26
21     14    36
22     14    60
23     14    80
24     15    20
25     15    26
26     15    54
27     16    32
28     16    40
29     17    32
30     17    40
31     17    50
32     18    42
33     18    56
34     18    76
35     18    84
36     19    36
37     19    46
38     19    68
39     20    32
40     20    48
41     20    52
42     20    56
43     20    64
44     22    66
45     23    54
46     24    70
47     24    92
48     24    93
49     24   120
50     25    85

In [12]:
df[['speed']].values.shape

(50, 1)

In [13]:
x= torch.FloatTensor( df[['speed']].values )
y= torch.FloatTensor( df[['dist']].values )

In [4]:
linear = Linear( 1,1 ) # 특성데이터갯수, 라벨의 갯수 w,b 

In [5]:
linear.weight

Parameter containing:
tensor([[-0.9168]], requires_grad=True)

In [6]:
linear.bias

Parameter containing:
tensor([0.2253], requires_grad=True)

In [8]:
list( linear.parameters() )

[Parameter containing:
 tensor([[-0.9168]], requires_grad=True),
 Parameter containing:
 tensor([0.2253], requires_grad=True)]

In [26]:
model = Sequential()
model.add_module( 'nn1', linear )
loss_fn = MSELoss()
optimizer = Adam( model.parameters(), lr= 0.1 )

In [27]:
for step in range(1000):
#     hx = linear.forward(x) # w*x + b
    hx = model.forward(x)
    # hx = linear(x)  #linear.forward(x)
    optimizer.zero_grad()
    c = loss_fn( hx, y )
    c.backward()
    optimizer.step()
    print( 'cost', c.item() )

cost 227.08685302734375
cost 229.41873168945312
cost 227.13735961914062
cost 227.89297485351562
cost 228.5557403564453
cost 227.8995361328125
cost 227.1739501953125
cost 227.1728973388672
cost 227.6392059326172
cost 227.8303680419922
cost 227.55746459960938
cost 227.18504333496094
cost 227.0819854736328
cost 227.2711944580078
cost 227.4677276611328
cost 227.4407196044922
cost 227.2431640625
cost 227.08755493164062
cost 227.10614013671875
cost 227.23370361328125
cost 227.30447387695312
cost 227.24330139160156
cost 227.1259002685547
cost 227.0728302001953
cost 227.1190948486328
cost 227.1901397705078
cost 227.19793701171875
cost 227.13812255859375
cost 227.08023071289062
cost 227.0807647705078
cost 227.12384033203125
cost 227.1492919921875
cost 227.1270751953125
cost 227.08621215820312
cost 227.07257080078125
cost 227.0937042236328
cost 227.11593627929688
cost 227.11000061035156
cost 227.08505249023438
cost 227.07164001464844
cost 227.08168029785156
cost 227.09689331054688
cost 227.09571

cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.0704345703125
cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.0704345703125
cost 227.07040405273438
cost 227.07040405273438
cost 227.07040405273438
cost 227.0704345703125
cost 227.0704345703125
cost 227.07044982910156
cost 227.07040405273438
cost 227.0704345703125
cost 227.0704345703125
cost 227.07044982910156
cost 227.07040405273438
cost 227.0704345703125
cost 227.0704345703125
cost 227.07044982910156
cost 227.07040405273438
cost 227.0704345703125
cost 227.0704345703125
cost 227.07040405273438
cost 227.07040405273438
cost 227.0704345703125
cost 227.0704345703125
cost 227.07040405273438
cost 227.07040405273438
cost 227.0704345703125
cost 227.0704345703125
cost 227.07040405273438
cost 227.07040405273438
cost 2

In [15]:
linear.weight

Parameter containing:
tensor([[3.5408]], requires_grad=True)

In [16]:
linear.bias

Parameter containing:
tensor([-10.8943], requires_grad=True)

In [22]:
linear.forward( torch.FloatTensor( [[5],[7]] ) )

tensor([[ 6.8095],
        [13.8910]], grad_fn=<AddmmBackward0>)

In [23]:
linear(  torch.FloatTensor( [[5],[7]] )  )

tensor([[ 6.8095],
        [13.8910]], grad_fn=<AddmmBackward0>)