In [1]:
import tensorflow as tf
from tensorflow.keras.optimizers import Adam, SGD
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler, StandardScaler

다중(특성데이터가 여러개)
1. 상관관계(corr):낮은것 컬럼제거
2. 다중공선성확인( statsmodel): 높은컬럼한개만 선택
3. 정규화(무조건)

In [2]:
data = [[828, 920, 1234567, 1020, 1111],
            [824, 910, 2345612, 1090, 1234],
            [880, 900, 3456123, 1010, 1000],
            [870, 990, 2312123, 1001, 1122],
            [860, 980, 3223123, 1008, 1133],
            [850, 970, 2432123, 1100, 1221]]
data = np.float32(data)

In [3]:
df = pd.DataFrame(data)
df

0      1          2       3       4
0  828.0  920.0  1234567.0  1020.0  1111.0
1  824.0  910.0  2345612.0  1090.0  1234.0
2  880.0  900.0  3456123.0  1010.0  1000.0
3  870.0  990.0  2312123.0  1001.0  1122.0
4  860.0  980.0  3223123.0  1008.0  1133.0
5  850.0  970.0  2432123.0  1100.0  1221.0

In [4]:
x_data = df.iloc[:,:-1]
y_data = df.iloc[:, [-1] ]

In [5]:
scaleF = MinMaxScaler()
x_dataN = scaleF.fit_transform( x_data)

In [6]:
scaleL = MinMaxScaler()
y_dataN = scaleL.fit_transform( y_data)

In [7]:
x_dataN

array([[0.0714283 , 0.22222233, 0.        , 0.19191933],
       [0.        , 0.11111164, 0.50012016, 0.89899063],
       [1.        , 0.        , 1.        , 0.09090996],
       [0.8214283 , 1.        , 0.48504567, 0.        ],
       [0.6428566 , 0.8888893 , 0.8951186 , 0.07070732],
       [0.4642849 , 0.7777777 , 0.5390618 , 1.        ]], dtype=float32)

In [8]:
y_dataN

array([[0.47435904],
       [1.0000005 ],
       [0.        ],
       [0.52136755],
       [0.56837654],
       [0.94444466]], dtype=float32)

In [9]:
x = tf.constant( x_dataN, tf.float32)
y = tf.constant( y_dataN, tf.float32)

In [10]:
w = tf.Variable( tf.random.uniform([4,1]) )#[특성데이터갯수, 라벨의갯수]
b = tf.Variable( tf.random.uniform([1]) ) # 라벨의 갯수

In [11]:
def cost():
    hx = tf.matmul( x, w ) + b
    c = tf.reduce_mean( (hx-y)**2)
    return c

In [12]:
optimizer = Adam( learning_rate=0.1 )
hist_cost=[]
for i in range( 1000):
    optimizer.minimize( cost, var_list=[w,b] )
    c = cost().numpy()
    hist_cost.append( c )
    print( i, 'cost=', c )

0 cost= 2.9712083
1 cost= 2.0540698
2 cost= 1.3290572
3 cost= 0.79229283
4 cost= 0.4336141
5 cost= 0.23476493
6 cost= 0.16838478
7 cost= 0.19902043
8 cost= 0.28692526
9 cost= 0.3938663
10 cost= 0.48876002
11 cost= 0.5511032
12 cost= 0.57155037
13 cost= 0.55028194
14 cost= 0.4942859
15 cost= 0.41449037
16 cost= 0.3232646
17 cost= 0.2324642
18 cost= 0.15201963
19 cost= 0.0890128
20 cost= 0.04720067
21 cost= 0.026969096
22 cost= 0.025702268
23 cost= 0.038525224
24 cost= 0.059316035
25 cost= 0.081821345
26 cost= 0.10067474
27 cost= 0.11213883
28 cost= 0.11446341
29 cost= 0.107846566
30 cost= 0.09407109
31 cost= 0.07593376
32 cost= 0.056600016
33 cost= 0.039000552
34 cost= 0.025358254
35 cost= 0.016902136
36 cost= 0.013790089
37 cost= 0.015229285
38 cost= 0.019751726
39 cost= 0.025578566
40 cost= 0.030995486
41 cost= 0.03466566
42 cost= 0.035827
43 cost= 0.03435016
44 cost= 0.030664906
45 cost= 0.025588244
46 cost= 0.02010215
47 cost= 0.015131711
48 cost= 0.011367366
49 cost= 0.009160169
50

386 cost= 0.0033241704
387 cost= 0.0033241597
388 cost= 0.0033241455
389 cost= 0.0033241317
390 cost= 0.0033241194
391 cost= 0.0033241073
392 cost= 0.003324094
393 cost= 0.0033240851
394 cost= 0.0033240754
395 cost= 0.0033240616
396 cost= 0.0033240542
397 cost= 0.0033240437
398 cost= 0.0033240374
399 cost= 0.0033240262
400 cost= 0.0033240186
401 cost= 0.0033240113
402 cost= 0.0033240032
403 cost= 0.0033239953
404 cost= 0.003323989
405 cost= 0.003323984
406 cost= 0.003323977
407 cost= 0.0033239706
408 cost= 0.003323964
409 cost= 0.0033239573
410 cost= 0.0033239534
411 cost= 0.0033239461
412 cost= 0.0033239415
413 cost= 0.003323938
414 cost= 0.0033239338
415 cost= 0.0033239285
416 cost= 0.0033239238
417 cost= 0.0033239194
418 cost= 0.0033239154
419 cost= 0.0033239126
420 cost= 0.0033239096
421 cost= 0.0033239059
422 cost= 0.003323904
423 cost= 0.0033238993
424 cost= 0.0033238968
425 cost= 0.0033238938
426 cost= 0.0033238914
427 cost= 0.0033238865
428 cost= 0.0033238863
429 cost= 0.003323

782 cost= 0.0033238332
783 cost= 0.0033238332
784 cost= 0.0033238332
785 cost= 0.0033238332
786 cost= 0.0033238332
787 cost= 0.0033238332
788 cost= 0.0033238332
789 cost= 0.0033238332
790 cost= 0.0033238332
791 cost= 0.0033238332
792 cost= 0.0033238332
793 cost= 0.0033238332
794 cost= 0.0033238332
795 cost= 0.0033238332
796 cost= 0.0033238332
797 cost= 0.0033238332
798 cost= 0.0033238332
799 cost= 0.0033238332
800 cost= 0.0033238332
801 cost= 0.0033238332
802 cost= 0.0033238332
803 cost= 0.0033238332
804 cost= 0.0033238332
805 cost= 0.0033238332
806 cost= 0.0033238332
807 cost= 0.0033238332
808 cost= 0.0033238332
809 cost= 0.0033238332
810 cost= 0.0033238332
811 cost= 0.0033238332
812 cost= 0.0033238332
813 cost= 0.0033238332
814 cost= 0.0033238332
815 cost= 0.0033238332
816 cost= 0.0033238332
817 cost= 0.0033238332
818 cost= 0.0033238332
819 cost= 0.0033238332
820 cost= 0.0033238332
821 cost= 0.0033238332
822 cost= 0.0033238332
823 cost= 0.0033238332
824 cost= 0.0033238332
825 cost= 0

In [13]:
def hxFn( xdata ):
    xd = tf.constant( xdata, tf.float32)
    hx = tf.matmul( xd, w ) + b
    return hx.numpy()

In [17]:
xn = scaleF.transform( [[828, 920, 1234567, 1020]] )

In [20]:
pred = hxFn( xn )

In [21]:
scaleL.inverse_transform( pred )

array([[1122.8623]], dtype=float32)