In [3]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam


In [4]:
df = pd.read_csv( 'data/softmax.txt', sep=' ',header=None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [6]:
x_data = df.iloc[:,:-3]
y_data = df.iloc[:,2:]

In [8]:
x_data.shape

(8, 2)

In [9]:
y_data.shape

(8, 3)

In [10]:
x = tf.constant( x_data, tf.float32)
y = tf.constant( y_data, tf.float32)

In [11]:
initX =tf.initializers.GlorotUniform()
w = tf.Variable( initX( shape=[2,3] ) ) # 특성데이터갯수, 라벨의 갯수
b = tf.Variable( initX( shape=[3] ) ) #라벨의갯수(분류의갯수)

C:\Users\NTX550\anaconda3\envs\mydeep\lib\site-packages\keras\initializers\initializers_v2.py:120: UserWarning: The initializer GlorotUniform is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(


In [12]:
def cost():
    z = tf.matmul(x,w) + b
#     hx = tf.nn.softmax( z )
    c_i = tf.nn.softmax_cross_entropy_with_logits( labels=y, logits=z)
    c = tf.reduce_mean( c_i )
    return c

In [13]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize( cost, var_list=[w,b] )
    print(i, 'cost:', cost().numpy() )

0 cost: 1.9023389
1 cost: 1.219993
2 cost: 1.2629676
3 cost: 1.5014367
4 cost: 1.6420643
5 cost: 1.6059308
6 cost: 1.4404871
7 cost: 1.2265518
8 cost: 1.0537176
9 cost: 1.0081263
10 cost: 1.0865185
11 cost: 1.1757784
12 cost: 1.1933811
13 cost: 1.1298528
14 cost: 1.0210868
15 cost: 0.92469096
16 cost: 0.8874128
17 cost: 0.90729487
18 cost: 0.9436596
19 cost: 0.95818293
20 cost: 0.9351427
21 cost: 0.8824951
22 cost: 0.8253949
23 cost: 0.7923764
24 cost: 0.7936883
25 cost: 0.8115362
26 cost: 0.8190574
27 cost: 0.8033513
28 cost: 0.7709514
29 cost: 0.73978305
30 cost: 0.72486687
31 cost: 0.7267479
32 cost: 0.7332461
33 cost: 0.7315099
34 cost: 0.7175133
35 cost: 0.69732654
36 cost: 0.6814985
37 cost: 0.6762166
38 cost: 0.67817205
39 cost: 0.6785942
40 cost: 0.6718181
41 cost: 0.65955174
42 cost: 0.64818656
43 cost: 0.64252996
44 cost: 0.64175373
45 cost: 0.64108723
46 cost: 0.6367232
47 cost: 0.6289034
48 cost: 0.62104905
49 cost: 0.6162765
50 cost: 0.6145336
51 cost: 0.6130496
52 cost: 0

420 cost: 0.2180595
421 cost: 0.21763432
422 cost: 0.21721034
423 cost: 0.21678767
424 cost: 0.21636614
425 cost: 0.21594584
426 cost: 0.21552674
427 cost: 0.21510884
428 cost: 0.21469215
429 cost: 0.21427657
430 cost: 0.21386224
431 cost: 0.21344909
432 cost: 0.21303704
433 cost: 0.21262625
434 cost: 0.21221657
435 cost: 0.21180806
436 cost: 0.21140069
437 cost: 0.21099445
438 cost: 0.21058938
439 cost: 0.21018544
440 cost: 0.20978257
441 cost: 0.20938092
442 cost: 0.20898032
443 cost: 0.20858082
444 cost: 0.20818244
445 cost: 0.20778519
446 cost: 0.20738903
447 cost: 0.20699397
448 cost: 0.20659995
449 cost: 0.20620707
450 cost: 0.2058152
451 cost: 0.20542449
452 cost: 0.20503484
453 cost: 0.20464623
454 cost: 0.20425868
455 cost: 0.20387219
456 cost: 0.20348668
457 cost: 0.2031023
458 cost: 0.20271888
459 cost: 0.20233661
460 cost: 0.2019553
461 cost: 0.2015751
462 cost: 0.20119587
463 cost: 0.20081761
464 cost: 0.20044039
465 cost: 0.20006424
466 cost: 0.19968906
467 cost: 0.199314

812 cost: 0.11165655
813 cost: 0.11148711
814 cost: 0.11131795
815 cost: 0.11114915
816 cost: 0.110980734
817 cost: 0.11081259
818 cost: 0.11064489
819 cost: 0.11047749
820 cost: 0.11031041
821 cost: 0.11014372
822 cost: 0.109977335
823 cost: 0.109811254
824 cost: 0.10964556
825 cost: 0.10948022
826 cost: 0.10931519
827 cost: 0.10915051
828 cost: 0.10898612
829 cost: 0.108822085
830 cost: 0.10865839
831 cost: 0.10849506
832 cost: 0.10833202
833 cost: 0.10816931
834 cost: 0.108006924
835 cost: 0.10784492
836 cost: 0.107683204
837 cost: 0.10752176
838 cost: 0.107360736
839 cost: 0.1072
840 cost: 0.10703958
841 cost: 0.106879495
842 cost: 0.10671973
843 cost: 0.10656033
844 cost: 0.10640122
845 cost: 0.10624236
846 cost: 0.10608395
847 cost: 0.1059258
848 cost: 0.10576795
849 cost: 0.105610415
850 cost: 0.10545319
851 cost: 0.1052963
852 cost: 0.10513971
853 cost: 0.10498346
854 cost: 0.104827516
855 cost: 0.104671896
856 cost: 0.10451658
857 cost: 0.10436159
858 cost: 0.10420689
859 cost

In [15]:
w.numpy()

array([[-0.2469048 , -0.35185903, -0.5934486 ],
       [ 3.067047  , -0.99242014, -5.6285076 ]], dtype=float32)

In [17]:
b.numpy()

array([-20.64888  ,   2.7435133,  23.801281 ], dtype=float32)

In [36]:
def hxFn( xdata ):
    xd = tf.constant( xdata, tf.float32)
    z = tf.matmul( xd, w ) + b
    hx = tf.nn.softmax( z )
    return hx.numpy().argmax(axis=1)
#     return z.numpy(), hx.numpy()

In [21]:
hxFn( [[5,5]])

array([[0.06878963, 0.8990504 , 0.03215992]], dtype=float32)

In [32]:
hx = hxFn( [[5,5]])
hx.argmax( axis=1)

array([1], dtype=int64)

In [34]:
hxFn( [[1,1],[5,7]] ).argmax( axis=1)

array([2, 0], dtype=int64)

In [37]:
hxFn( [[1,1],[5,7]] )

array([2, 0], dtype=int64)

In [45]:
pred = hxFn( x )
pred

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [43]:
real = y.numpy().argmax(axis=1)
real

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [47]:
(pred==real).mean()

1.0

In [28]:
arr =np.array([[1,22],[3,4]])
arr

array([[ 1, 22],
       [ 3,  4]])

In [29]:
arr.argmax()

1

In [30]:
arr.argmax(axis=0)

array([1, 0], dtype=int64)

In [31]:
arr.argmax(axis=1)

array([1, 1], dtype=int64)

In [ ]:
axis=None 전체에 대한
axis=0 컬럼단위
axis=1 행단위

In [24]:
arr.sum()

10

In [25]:
arr.sum(axis=0)

array([4, 6])

In [26]:
arr.sum(axis=1)

array([3, 7])