In [2]:
import torch
from torch.optim import Adam
from torch.nn import Linear, CrossEntropyLoss, Sequential, Softmax

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv( 'data/softmax.txt', sep=' ',header=None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [4]:
x_data = df.iloc[:,:-3].values
y_data = df.iloc[:,2:].values

In [5]:
x = torch.FloatTensor( x_data )
y = torch.FloatTensor( y_data )

In [19]:
model = Sequential()
model.add_module( 'nn1', Linear(2,3) ) # w:2x3, b:3 
model.add_module( 'soft1', Softmax(dim=1) ) #활성함수.
loss_fn = CrossEntropyLoss()
optimizer = Adam( model.parameters(), lr=0.1 )

In [20]:
for epoch in range(2000):
    optimizer.zero_grad()
    hx = model(x) # model.forward(x)  z = matmul( x,w) +b ==> Softmax( z , dim=1)
    c = loss_fn( hx, y) 
    c.backward()
    optimizer.step()
    print( epoch, c.item() )

0 1.1368212699890137
1 1.12208890914917
2 1.0944701433181763
3 1.0582239627838135
4 1.0462160110473633
5 1.0542504787445068
6 1.045044183731079
7 1.0260660648345947
8 1.0113232135772705
9 1.004485845565796
10 1.004483938217163
11 1.0004020929336548
12 0.9875587821006775
13 0.9754385948181152
14 0.9693966507911682
15 0.966865599155426
16 0.9634155035018921
17 0.9567641019821167
18 0.9484832286834717
19 0.9415034055709839
20 0.9372755289077759
21 0.9348560571670532
22 0.9314769506454468
23 0.9260104894638062
24 0.9202359914779663
25 0.9158034920692444
26 0.9127525687217712
27 0.910089373588562
28 0.9067051410675049
29 0.9025834202766418
30 0.8984931111335754
31 0.8949000835418701
32 0.8919259309768677
33 0.8892499804496765
34 0.8861832618713379
35 0.8826093077659607
36 0.8790990710258484
37 0.8760203719139099
38 0.8732742071151733
39 0.8706165552139282
40 0.8677887916564941
41 0.8647826910018921
42 0.8618606328964233
43 0.859200119972229
44 0.856826901435852
45 0.8546169400215149
46 0.85

672 0.5951927900314331
673 0.5951006412506104
674 0.5950087308883667
675 0.5949170589447021
676 0.5948256850242615
677 0.5947345495223999
678 0.5946437120437622
679 0.5945532321929932
680 0.5944628715515137
681 0.5943728685379028
682 0.5942831039428711
683 0.5941936373710632
684 0.5941044688224792
685 0.5940155982971191
686 0.5939268469810486
687 0.5938384532928467
688 0.5937502980232239
689 0.5936623811721802
690 0.5935747623443604
691 0.5934873819351196
692 0.5934003591537476
693 0.593313455581665
694 0.5932269096374512
695 0.5931406021118164
696 0.593054473400116
697 0.5929686427116394
698 0.5928831100463867
699 0.5927977561950684
700 0.5927127003669739
701 0.5926278829574585
702 0.592543363571167
703 0.5924590826034546
704 0.5923749804496765
705 0.5922911167144775
706 0.5922076106071472
707 0.5921242237091064
708 0.5920411348342896
709 0.5919583439826965
710 0.5918757915496826
711 0.591793417930603
712 0.5917112827301025
713 0.5916293859481812
714 0.5915477275848389
715 0.591466367

1343 0.5660791397094727
1344 0.5660603046417236
1345 0.5660415887832642
1346 0.5660228729248047
1347 0.56600421667099
1348 0.5659855604171753
1349 0.5659669637680054
1350 0.5659483671188354
1351 0.5659297704696655
1352 0.5659112930297852
1353 0.5658928155899048
1354 0.5658743977546692
1355 0.5658559799194336
1356 0.5658376216888428
1357 0.565819263458252
1358 0.5658009052276611
1359 0.5657827854156494
1360 0.5657644867897034
1361 0.5657463073730469
1362 0.5657280683517456
1363 0.5657099485397339
1364 0.5656918883323669
1365 0.5656737685203552
1366 0.5656557679176331
1367 0.5656377077102661
1368 0.5656197667121887
1369 0.5656018257141113
1370 0.5655839443206787
1371 0.5655660629272461
1372 0.5655482411384583
1373 0.5655304193496704
1374 0.5655126571655273
1375 0.5654948949813843
1376 0.565477192401886
1377 0.5654594898223877
1378 0.5654418468475342
1379 0.5654242634773254
1380 0.5654066205024719
1381 0.5653891563415527
1382 0.5653716325759888
1383 0.5653541088104248
1384 0.5653367042541

In [14]:
model[0].weight

Parameter containing:
tensor([[-0.9416, -0.5644],
        [ 0.6681,  5.1671],
        [ 0.4340, -3.6930]], requires_grad=True)

In [15]:
model[0].bias

Parameter containing:
tensor([ -1.1331, -21.6791,  18.3713], requires_grad=True)

In [13]:
list( model[0].parameters() )

[Parameter containing:
 tensor([[-0.9416, -0.5644],
         [ 0.6681,  5.1671],
         [ 0.4340, -3.6930]], requires_grad=True),
 Parameter containing:
 tensor([ -1.1331, -21.6791,  18.3713], requires_grad=True)]

In [21]:
model( torch.FloatTensor([[1,1],[5,6]]) ).argmax( dim=1 )

tensor([2, 0])