In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU

In [3]:
x = np.array( [[1,2,3], [2,3,4], [3,4,5], [4,5,6]] )
y = np.array( [4,5,6,7] )

In [4]:
# ( batch_size, sequence length, hidden size)
# hidden size = 특성데이터갯수
x = x.reshape( 4, 3, 1)
x

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]]])

In [5]:
model = Sequential()
model.add( SimpleRNN(50, activation='relu', input_shape=(3,1) ) )
model.add( Dense( units=32))
model.add( Dense( units=1))
model.compile( loss='mse', optimizer='adam')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 1s/step - loss: 49.0450
Epoch 2/1000
1/1 [==============================] - 0s 10ms/step - loss: 44.4091
Epoch 3/1000
1/1 [==============================] - 0s 9ms/step - loss: 40.0279
Epoch 4/1000
1/1 [==============================] - 0s 7ms/step - loss: 35.8998
Epoch 5/1000
1/1 [==============================] - 0s 10ms/step - loss: 32.0240
Epoch 6/1000
1/1 [==============================] - 0s 9ms/step - loss: 28.3853
Epoch 7/1000
1/1 [==============================] - 0s 9ms/step - loss: 24.9826
Epoch 8/1000
1/1 [==============================] - 0s 9ms/step - loss: 21.8133
Epoch 9/1000
1/1 [==============================] - 0s 9ms/step - loss: 18.8678
Epoch 10/1000
1/1 [==============================] - 0s 7ms/step - loss: 16.1381
Epoch 11/1000
1/1 [==============================] - 0s 8ms/step - loss: 13.6254
Epoch 12/1000
1/1 [==============================] - 0s 10ms/step - loss: 11.3306
Epoch 13/1000
1/1 [================

In [6]:
w = model.layers[0].get_weights()

In [7]:
len(w)

3

In [8]:
print(w[0].shape)
print(w[1].shape)
print(w[2].shape)

(1, 50)
(50, 50)
(50,)


In [9]:
w,b = model.layers[1].get_weights()

In [10]:
w.shape

(50, 32)

In [12]:
model.predict( np.array([7,8,9]).reshape(1,3,1))

1/1 [==============================] - 0s 229ms/step


array([[10.357863]], dtype=float32)

In [21]:
x = np.array( [[1,2,3], [2,3,4], [3,4,5], [4,5,6], [5,6,7],
            [6,7,8], [7,8,9], [8,9,10], [9,10,11], [10,11,12],
            [20,30,40], [30,40,50], [40,50,60]],dtype=np.float32 )
y = np.array([4,5,6,7,8,9,10,11,12,13,50,60,70],dtype=np.float32) 

In [22]:
x.shape

(13, 3)

In [23]:
x = x.reshape(-1, 3, 1)
x.shape

(13, 3, 1)

In [24]:
model = Sequential()
model.add( SimpleRNN(50, activation='relu', input_shape=(3,1) ) )
model.add( Dense( units=32))
model.add( Dense( units=1))
model.compile( loss='mse', optimizer='adam')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 1s/step - loss: 1009.2195
Epoch 2/1000
1/1 [==============================] - 0s 9ms/step - loss: 904.8265
Epoch 3/1000
1/1 [==============================] - 0s 9ms/step - loss: 806.5359
Epoch 4/1000
1/1 [==============================] - 0s 9ms/step - loss: 713.9628
Epoch 5/1000
1/1 [==============================] - 0s 9ms/step - loss: 626.9003
Epoch 6/1000
1/1 [==============================] - 0s 9ms/step - loss: 545.3642
Epoch 7/1000
1/1 [==============================] - 0s 7ms/step - loss: 469.9062
Epoch 8/1000
1/1 [==============================] - 0s 8ms/step - loss: 400.5450
Epoch 9/1000
1/1 [==============================] - 0s 7ms/step - loss: 336.5643
Epoch 10/1000
1/1 [==============================] - 0s 6ms/step - loss: 278.0184
Epoch 11/1000
1/1 [==============================] - 0s 9ms/step - loss: 224.9190
Epoch 12/1000
1/1 [==============================] - 0s 6ms/step - loss: 177.1900
Epoch 13/1000
1/1 [======

In [26]:
model.predict( np.array([55,65,75]).reshape(1,3,1))

1/1 [==============================] - 0s 31ms/step


array([[84.973915]], dtype=float32)