In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU

In [4]:
df = pd.read_csv('data/sample.csv', index_col='date')
df

x
date           
2021-01-01    1
2021-01-02    2
2021-01-03    3
2021-01-04    4
2021-01-05    5
...         ...
2021-04-06   96
2021-04-07   97
2021-04-08   98
2021-04-09   99
2021-04-10  100

[100 rows x 1 columns]

In [5]:
df.shift(-1)

x
date             
2021-01-01    2.0
2021-01-02    3.0
2021-01-03    4.0
2021-01-04    5.0
2021-01-05    6.0
...           ...
2021-04-06   97.0
2021-04-07   98.0
2021-04-08   99.0
2021-04-09  100.0
2021-04-10    NaN

[100 rows x 1 columns]

In [6]:
df['y'] = df.shift(-1)

In [13]:
df['x_2'] = df['x'].shift(2)

In [ ]:
df['x_1'] = df['x'].shift(1)

In [15]:
df['x_0'] = df['x'].shift(0)

In [18]:
df.dropna( inplace=True)

In [19]:
df = df.astype(int)

In [20]:
df

x    y  x_2  x_1  x_0
date                              
2021-01-03   3    4    1    2    3
2021-01-04   4    5    2    3    4
2021-01-05   5    6    3    4    5
2021-01-06   6    7    4    5    6
2021-01-07   7    8    5    6    7
...         ..  ...  ...  ...  ...
2021-04-05  95   96   93   94   95
2021-04-06  96   97   94   95   96
2021-04-07  97   98   95   96   97
2021-04-08  98   99   96   97   98
2021-04-09  99  100   97   98   99

[97 rows x 5 columns]

In [21]:
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset) -1:
            break
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)


def split_xy2(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 추가
        # if end_number > len(dataset) -1:
        # break
        if y_end_number > len(dataset): # 수정
            break
        tmp_x = dataset[i : x_end_number]
        tmp_y = dataset[x_end_number : y_end_number] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [24]:
df = pd.read_csv('data/sample.csv', index_col='date')

In [25]:
x, y = split_xy1(df['x'].values, 4)
print(x)
print('================================')
print(y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]
 [17 18 19 20]
 [18 19 20 21]
 [19 20 21 22]
 [20 21 22 23]
 [21 22 23 24]
 [22 23 24 25]
 [23 24 25 26]
 [24 25 26 27]
 [25 26 27 28]
 [26 27 28 29]
 [27 28 29 30]
 [28 29 30 31]
 [29 30 31 32]
 [30 31 32 33]
 [31 32 33 34]
 [32 33 34 35]
 [33 34 35 36]
 [34 35 36 37]
 [35 36 37 38]
 [36 37 38 39]
 [37 38 39 40]
 [38 39 40 41]
 [39 40 41 42]
 [40 41 42 43]
 [41 42 43 44]
 [42 43 44 45]
 [43 44 45 46]
 [44 45 46 47]
 [45 46 47 48]
 [46 47 48 49]
 [47 48 49 50]
 [48 49 50 51]
 [49 50 51 52]
 [50 51 52 53]
 [51 52 53 54]
 [52 53 54 55]
 [53 54 55 56]
 [54 55 56 57]
 [55 56 57 58]
 [56 57 58 59]
 [57 58 59 60]
 [58 59 60 61]
 [59 60 61 62]
 [60 61 62 63]
 [61 62 63 64]
 [62 63 64 65]
 [63 64 65 66]
 [64 65 66 67]
 [65 66 67 68]
 [66 67 68 69]
 [67 68 69

In [26]:
x, y = split_xy2(df['x'].values, 3, 2)
print(x)
print('================================')
print(y)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]
 [23 24 25]
 [24 25 26]
 [25 26 27]
 [26 27 28]
 [27 28 29]
 [28 29 30]
 [29 30 31]
 [30 31 32]
 [31 32 33]
 [32 33 34]
 [33 34 35]
 [34 35 36]
 [35 36 37]
 [36 37 38]
 [37 38 39]
 [38 39 40]
 [39 40 41]
 [40 41 42]
 [41 42 43]
 [42 43 44]
 [43 44 45]
 [44 45 46]
 [45 46 47]
 [46 47 48]
 [47 48 49]
 [48 49 50]
 [49 50 51]
 [50 51 52]
 [51 52 53]
 [52 53 54]
 [53 54 55]
 [54 55 56]
 [55 56 57]
 [56 57 58]
 [57 58 59]
 [58 59 60]
 [59 60 61]
 [60 61 62]
 [61 62 63]
 [62 63 64]
 [63 64 65]
 [64 65 66]
 [65 66 67]
 [66 67 68]
 [67 68 69]
 [68 69 70]
 [69 70 71]
 [70 71 72]
 [71 72 73]
 [72 73 74]
 [73 74 75]
 [74 75 76]
 [75 76 77]
 [76 77 78]
 [77 78 79]
 [78 79 80]
 [79 80 81]
 [80 81 82]
 [81 82 83]
 [82 83 84]
 [83 84 85]
 [84

In [27]:
# 10분퀴즈
# RNN으로 학습하고
# 80, 81, 82 인 경우 예측값을 구하시오.

In [28]:
model = Sequential()
model.add( SimpleRNN(50, activation='relu', input_shape=(3,1) ) )
model.add( Dense( units=32))
model.add( Dense( units=1))
model.compile( loss='mse', optimizer='adam')
model.fit(x, y, epochs=1000)

Epoch 1/1000
3/3 [==============================] - 1s 3ms/step - loss: 673.6608
Epoch 2/1000
3/3 [==============================] - 0s 2ms/step - loss: 152.3930
Epoch 3/1000
3/3 [==============================] - 0s 3ms/step - loss: 9.9645
Epoch 4/1000
3/3 [==============================] - 0s 2ms/step - loss: 72.1593
Epoch 5/1000
3/3 [==============================] - 0s 4ms/step - loss: 110.4455
Epoch 6/1000
3/3 [==============================] - 0s 2ms/step - loss: 56.5342
Epoch 7/1000
3/3 [==============================] - 0s 4ms/step - loss: 9.2080
Epoch 8/1000
3/3 [==============================] - 0s 3ms/step - loss: 5.4540
Epoch 9/1000
3/3 [==============================] - 0s 3ms/step - loss: 19.7946
Epoch 10/1000
3/3 [==============================] - 0s 3ms/step - loss: 23.7516
Epoch 11/1000
3/3 [==============================] - 0s 3ms/step - loss: 13.5043
Epoch 12/1000
3/3 [==============================] - 0s 4ms/step - loss: 2.8676
Epoch 13/1000
3/3 [===================

In [29]:
model.predict( np.array([80,81,82]).reshape(1,3,1))

1/1 [==============================] - 0s 131ms/step


array([[83.51216]], dtype=float32)