In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU

In [3]:
df = pd.read_csv('data/sample1.csv', index_col='date')
df

a    b    y
date                     
2021-01-01    1   21    4
2021-01-02    2   22    5
2021-01-03    3   23    6
2021-01-04    4   24    7
2021-01-05    5   25    8
...         ...  ...  ...
2021-04-06   96  116   99
2021-04-07   97  117  100
2021-04-08   98  118  101
2021-04-09   99  119  102
2021-04-10  100  120  103

[100 rows x 3 columns]

In [4]:
def make_dataset(data, label, window_size=20):
    feature_list = []
    label_list = []
    for i in range(len(data) - window_size):
        feature_list.append(np.array(data.iloc[i:i+window_size]))
        label_list.append(np.array(label.iloc[i+window_size]))
    return np.array(feature_list), np.array(label_list)

### 값 1개 예측

In [5]:
# data, label, window size
x, y = make_dataset( df[['a', 'b']], df['a'], 4 )

In [13]:
x

array([[[  1,  21],
        [  2,  22],
        [  3,  23],
        [  4,  24]],

       [[  2,  22],
        [  3,  23],
        [  4,  24],
        [  5,  25]],

       [[  3,  23],
        [  4,  24],
        [  5,  25],
        [  6,  26]],

       [[  4,  24],
        [  5,  25],
        [  6,  26],
        [  7,  27]],

       [[  5,  25],
        [  6,  26],
        [  7,  27],
        [  8,  28]],

       [[  6,  26],
        [  7,  27],
        [  8,  28],
        [  9,  29]],

       [[  7,  27],
        [  8,  28],
        [  9,  29],
        [ 10,  30]],

       [[  8,  28],
        [  9,  29],
        [ 10,  30],
        [ 11,  31]],

       [[  9,  29],
        [ 10,  30],
        [ 11,  31],
        [ 12,  32]],

       [[ 10,  30],
        [ 11,  31],
        [ 12,  32],
        [ 13,  33]],

       [[ 11,  31],
        [ 12,  32],
        [ 13,  33],
        [ 14,  34]],

       [[ 12,  32],
        [ 13,  33],
        [ 14,  34],
        [ 15,  35]],

       [[ 13,  3

In [12]:
x.shape

(96, 4, 2)

In [14]:
model = Sequential()
model.add( SimpleRNN(50, activation='relu', input_shape=(4,2) ) )
model.add( Dense( units=32))
model.add( Dense( units=1))
model.compile( loss='mse', optimizer='adam')
model.fit(x, y, epochs=1000)

Epoch 1/1000
3/3 [==============================] - 1s 4ms/step - loss: 1169.1656
Epoch 2/1000
3/3 [==============================] - 0s 3ms/step - loss: 77.7249
Epoch 3/1000
3/3 [==============================] - 0s 2ms/step - loss: 237.9951
Epoch 4/1000
3/3 [==============================] - 0s 2ms/step - loss: 284.7295
Epoch 5/1000
3/3 [==============================] - 0s 3ms/step - loss: 83.2288
Epoch 6/1000
3/3 [==============================] - 0s 2ms/step - loss: 10.1350
Epoch 7/1000
3/3 [==============================] - 0s 4ms/step - loss: 68.7412
Epoch 8/1000
3/3 [==============================] - 0s 3ms/step - loss: 78.8467
Epoch 9/1000
3/3 [==============================] - 0s 3ms/step - loss: 30.3631
Epoch 10/1000
3/3 [==============================] - 0s 2ms/step - loss: 2.6453
Epoch 11/1000
3/3 [==============================] - 0s 2ms/step - loss: 13.2878
Epoch 12/1000
3/3 [==============================] - 0s 4ms/step - loss: 22.6362
Epoch 13/1000
3/3 [===============

In [18]:
t = np.array([[29,49], [30, 50], [31, 51], [32,52]])
t

array([[29, 49],
       [30, 50],
       [31, 51],
       [32, 52]])

In [17]:
# 값 한개 예측
model.predict(t.reshape(1,4,2))

1/1 [==============================] - 0s 190ms/step


array([[32.97842]], dtype=float32)

### 값 2개 예측

In [19]:
x, y = make_dataset(df[['a','b']], df[['a', 'b']], 4)

In [20]:
x.shape

(96, 4, 2)

In [21]:
model = Sequential()
model.add(SimpleRNN(30, activation='relu', input_shape=(4,2)) ) #units = hidden size 갯수
model.add(Dense(units=32))
model.add(Dense(units=2))
model.compile(loss='mse', optimizer='adam')
model.fit(x,y, epochs=1000)

Epoch 1/1000
3/3 [==============================] - 1s 3ms/step - loss: 4413.8911
Epoch 2/1000
3/3 [==============================] - 0s 2ms/step - loss: 2926.2981
Epoch 3/1000
3/3 [==============================] - 0s 3ms/step - loss: 1658.7174
Epoch 4/1000
3/3 [==============================] - 0s 2ms/step - loss: 818.8469
Epoch 5/1000
3/3 [==============================] - 0s 2ms/step - loss: 262.0962
Epoch 6/1000
3/3 [==============================] - 0s 2ms/step - loss: 36.1600
Epoch 7/1000
3/3 [==============================] - 0s 3ms/step - loss: 58.4496
Epoch 8/1000
3/3 [==============================] - 0s 2ms/step - loss: 163.7277
Epoch 9/1000
3/3 [==============================] - 0s 2ms/step - loss: 202.7390
Epoch 10/1000
3/3 [==============================] - 0s 3ms/step - loss: 149.9270
Epoch 11/1000
3/3 [==============================] - 0s 3ms/step - loss: 71.0572
Epoch 12/1000
3/3 [==============================] - 0s 3ms/step - loss: 23.1815
Epoch 13/1000
3/3 [=======

In [22]:
t = np.array([[29,49], [30, 50], [31, 51], [32,52]])

In [23]:
# 값 2개 예측 결과가 나온다
model.predict(t.reshape(1,4,2))

1/1 [==============================] - 0s 99ms/step


array([[32.919754, 52.93035 ]], dtype=float32)