In [1]:
import torch

In [2]:
aa = torch.tensor( 100 )
aa

tensor(100)

In [4]:
aa.item()

100

In [9]:
# bb = torch.tensor( [10,20,30,40] , dtype=torch.int32)
bb = torch.tensor( [10,20,30,40] , dtype=torch.float32)
bb

tensor([10., 20., 30., 40.])

In [8]:
cc = torch.IntTensor([10,20,30,40]  )

In [7]:
dd = torch.LongTensor([10,20,30,40]  )

In [ ]:
dd = torch.FloatTensor([10,20,30,40]  )

In [5]:
bb.numpy()

array([10, 20, 30, 40], dtype=int64)

In [10]:
a = torch.tensor( 3 )
b = torch.tensor([10,20,30])
c = torch.multiply( a, b) # c = a*b
# c = b.multiply(a)

In [11]:
c

tensor([30, 60, 90])

In [ ]:
b.mean() # torch.mean(b)