In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv( 'data/test.csv', header=None)
df.columns = ['q1','q2','mid','final']
df

q1  q2  mid  final
0   73  80   75    152
1   93  88   93    185
2   89  91   90    180
3   96  98  100    196
4   73  66   70    142
5   53  46   55    101
6   69  74   77    149
7   47  56   60    115
8   87  79   90    175
9   79  70   88    164
10  69  70   73    141
11  70  65   74    141
12  93  95   91    184
13  79  80   73    152
14  70  73   78    148
15  93  89   96    192
16  78  75   68    147
17  81  90   93    183
18  88  92   86    177
19  78  83   77    159
20  82  86   90    177
21  86  82   89    175
22  78  83   85    175
23  76  83   71    149
24  96  93   95    192

In [3]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1] ].values

In [4]:
x = torch.FloatTensor( x_data )
y = torch.FloatTensor( y_data )

In [5]:
model = Sequential()
model.add_module( 'nn1', Linear(3,1) ) # w: 3x1, b:1
loss_fn = MSELoss()
optimizer = Adam( model.parameters(), lr=0.1 )

In [6]:
for epoch in range(1000):
    optimizer.zero_grad()
    hx = model.forward( x ) # matmul( x,w) +b 
    # hx = model(x)
    c = loss_fn( hx, y) 
    c.backward()
    optimizer.step()
    print( epoch, c.item() )

0 10174.4873046875
1 5858.55810546875
2 2769.607421875
3 878.7548217773438
4 74.68142700195312
5 127.51597595214844
6 688.9495849609375
7 1369.97607421875
8 1867.3035888671875
9 2040.0137939453125
10 1894.5648193359375
11 1524.2998046875
12 1053.0472412109375
13 597.8605346679688
14 247.49053955078125
15 51.1310920715332
16 15.02679443359375
17 107.0171127319336
18 269.1403503417969
19 435.93988037109375
20 553.0374755859375
21 589.9029541015625
22 543.5560913085938
23 433.97686767578125
24 294.54296875
25 161.1305389404297
26 62.63579177856445
27 14.67444133758545
28 17.386201858520508
29 57.480377197265625
30 113.6943359375
31 163.88455200195312
32 191.48863220214844
33 189.44920349121094
34 160.7466278076172
35 115.90962219238281
36 68.72770690917969
37 31.678598403930664
38 12.41099739074707
39 12.14265251159668
40 26.210817337036133
41 46.36286544799805
42 63.87273406982422
43 72.38215637207031
44 69.57466125488281
45 57.29059982299805
46 40.269161224365234
47 24.130388259887695
4

845 6.079019069671631
846 6.078528881072998
847 6.078042984008789
848 6.07753849029541
849 6.077061176300049
850 6.076575756072998
851 6.0760884284973145
852 6.075613975524902
853 6.075125694274902
854 6.074650764465332
855 6.074179649353027
856 6.07370662689209
857 6.07322883605957
858 6.072762489318848
859 6.072283744812012
860 6.071823596954346
861 6.0713629722595215
862 6.070908069610596
863 6.070449352264404
864 6.069981575012207
865 6.069526195526123
866 6.069065093994141
867 6.0686140060424805
868 6.068166732788086
869 6.067712783813477
870 6.067267894744873
871 6.066824913024902
872 6.066375255584717
873 6.065937042236328
874 6.065488815307617
875 6.0650553703308105
876 6.064619064331055
877 6.064174652099609
878 6.063741683959961
879 6.063311576843262
880 6.0628743171691895
881 6.062442779541016
882 6.062014579772949
883 6.061590671539307
884 6.061160087585449
885 6.060750961303711
886 6.060324668884277
887 6.059901237487793
888 6.059481143951416
889 6.059066295623779
890 6.05

In [7]:
model[0].weight #결과는

Parameter containing:
tensor([[0.3392, 0.5487, 1.1323]], requires_grad=True)

In [8]:
model( torch.FloatTensor( [[90,90,100]] ) )

tensor([[192.5725]], grad_fn=<AddmmBackward0>)

In [11]:
model( torch.FloatTensor( [[50,60,70], [90,90,100] ] ) ).detach().numpy()

array([[128.57492],
       [192.57251]], dtype=float32)