In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam

In [2]:
x_data = np.array( [[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]]) # 공부한시간,출석일수
y_data = np.array( [[0],[0],[0],[1],[1],[1]])

In [7]:
x_data.shape

(6, 2)

In [3]:
x = tf.constant( x_data, tf.float32)
y = tf.constant( y_data, tf.float32)

In [4]:
# xavier, he( 최적의 초기화 알고리즘)
initX =tf.initializers.GlorotUniform()
w = tf.Variable( initX( shape=[2,1] ) )
b = tf.Variable( initX( shape=[1] ) )

C:\Users\NTX550\anaconda3\lib\site-packages\keras\initializers\initializers_v2.py:120: UserWarning: The initializer GlorotUniform is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(


In [8]:
def cost():
    z = tf.matmul(x,w) + b
    #     hx = tf.nn.sigmoid(z)
    c_i = tf.nn.sigmoid_cross_entropy_with_logits( labels=y, logits=z)
    c = tf.reduce_mean( c_i )
    return c

In [9]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize( cost, var_list=[w,b] )
    print(i, 'cost:', cost().numpy() )

0 cost: 4.8249927
1 cost: 4.278481
2 cost: 3.7343194
3 cost: 3.1941888
4 cost: 2.6611302
5 cost: 2.1410577
6 cost: 1.6462517
7 cost: 1.202078
8 cost: 0.851734
9 cost: 0.6384353
10 cost: 0.5657939
11 cost: 0.5909005
12 cost: 0.66165334
13 cost: 0.7436735
14 cost: 0.8198032
15 cost: 0.8825311
16 cost: 0.9290455
17 cost: 0.95881015
18 cost: 0.9724199
19 cost: 0.97104526
20 cost: 0.95615935
21 cost: 0.9294043
22 cost: 0.8925325
23 cost: 0.8473885
24 cost: 0.7959133
25 cost: 0.740161
26 cost: 0.682321
27 cost: 0.62473774
28 cost: 0.5699172
29 cost: 0.52049273
30 cost: 0.47910175
31 cost: 0.44809926
32 cost: 0.42905986
33 cost: 0.42213657
34 cost: 0.42555594
35 cost: 0.4356401
36 cost: 0.44755325
37 cost: 0.45653537
38 cost: 0.45909563
39 cost: 0.45371863
40 cost: 0.44093713
41 cost: 0.42287278
42 cost: 0.40246022
43 cost: 0.3826019
44 cost: 0.36549354
45 cost: 0.35228574
46 cost: 0.3431097
47 cost: 0.33735242
48 cost: 0.33401358
49 cost: 0.3320121
50 cost: 0.33038977
51 cost: 0.32841468
52 

431 cost: 0.021847427
432 cost: 0.021769911
433 cost: 0.021692833
434 cost: 0.021616193
435 cost: 0.02153998
436 cost: 0.021464193
437 cost: 0.021388834
438 cost: 0.021313893
439 cost: 0.021239372
440 cost: 0.021165267
441 cost: 0.021091571
442 cost: 0.021018295
443 cost: 0.020945415
444 cost: 0.020872945
445 cost: 0.020800864
446 cost: 0.020729184
447 cost: 0.020657899
448 cost: 0.020587007
449 cost: 0.020516498
450 cost: 0.020446382
451 cost: 0.02037664
452 cost: 0.020307286
453 cost: 0.020238297
454 cost: 0.020169692
455 cost: 0.02010145
456 cost: 0.020033574
457 cost: 0.019966066
458 cost: 0.019898927
459 cost: 0.019832138
460 cost: 0.019765718
461 cost: 0.019699642
462 cost: 0.019633917
463 cost: 0.019568546
464 cost: 0.01950352
465 cost: 0.019438835
466 cost: 0.019374495
467 cost: 0.019310495
468 cost: 0.019246832
469 cost: 0.019183496
470 cost: 0.019120494
471 cost: 0.019057827
472 cost: 0.018995492
473 cost: 0.018933471
474 cost: 0.018871779
475 cost: 0.018810403
476 cost: 0.01

817 cost: 0.0079758465
818 cost: 0.0079600345
819 cost: 0.007944268
820 cost: 0.007928551
821 cost: 0.007912886
822 cost: 0.007897266
823 cost: 0.007881694
824 cost: 0.007866169
825 cost: 0.0078506945
826 cost: 0.007835264
827 cost: 0.00781988
828 cost: 0.0078045423
829 cost: 0.0077892523
830 cost: 0.0077740117
831 cost: 0.007758811
832 cost: 0.00774366
833 cost: 0.0077285543
834 cost: 0.007713498
835 cost: 0.007698482
836 cost: 0.0076835104
837 cost: 0.007668587
838 cost: 0.0076537137
839 cost: 0.0076388777
840 cost: 0.0076240893
841 cost: 0.0076093436
842 cost: 0.0075946413
843 cost: 0.0075799823
844 cost: 0.007565368
845 cost: 0.0075507984
846 cost: 0.0075362697
847 cost: 0.0075217844
848 cost: 0.0075073442
849 cost: 0.0074929446
850 cost: 0.007478588
851 cost: 0.007464276
852 cost: 0.0074500046
853 cost: 0.0074357777
854 cost: 0.007421592
855 cost: 0.0074074455
856 cost: 0.00739334
857 cost: 0.007379279
858 cost: 0.0073652617
859 cost: 0.0073512834
860 cost: 0.007337348
861 cost: 0

In [19]:
def hxFn( xdata ):
    xd = tf.constant( xdata, tf.float32)
    z = tf.matmul( xd, w ) + b
    hx = tf.nn.sigmoid( z )
    return (hx.numpy()>0.5) + 0
#     return z.numpy(), hx.numpy()

In [20]:
hxFn( [[5,5]] )

array([[1]])

In [21]:
hxFn( [[1,1]] )

array([[0]])

In [26]:
pred = hxFn( x_data )
pred

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [28]:
(pred == y_data).mean()

1.0

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy_score( y_data, pred )

1.0