In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
import numpy as np

In [3]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y_data = np.array( [[0],[1],[1],[0] ] )

In [4]:
model_logi = LogisticRegression( max_iter=1000, verbose=1)
model_logi.fit( x_data, y_data )

C:\Users\NTX550\anaconda3\envs\mydeep\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(max_iter=1000, verbose=1)

In [5]:
model_logi.predict( x_data )

array([0, 0, 0, 0])

In [6]:
model_logi.score( x_data, y_data)

0.5

In [11]:
model_logi.coef_

array([[0., 0.]])

In [12]:
model_logi.intercept_

array([0.])

In [8]:
### 딥러닝
model_mlp = MLPClassifier( verbose=True, max_iter=1000)
model_mlp.fit( x_data, y_data)

Iteration 1, loss = 0.66830937
Iteration 2, loss = 0.66709246
Iteration 3, loss = 0.66594948
Iteration 4, loss = 0.66487706
Iteration 5, loss = 0.66379442
Iteration 6, loss = 0.66271776
Iteration 7, loss = 0.66163413
Iteration 8, loss = 0.66053896
Iteration 9, loss = 0.65944453
Iteration 10, loss = 0.65833974
Iteration 11, loss = 0.65723950
Iteration 12, loss = 0.65615260
Iteration 13, loss = 0.65508720
Iteration 14, loss = 0.65403926
Iteration 15, loss = 0.65301004
Iteration 16, loss = 0.65197291
Iteration 17, loss = 0.65092844
Iteration 18, loss = 0.64990117
Iteration 19, loss = 0.64891486
Iteration 20, loss = 0.64792577
Iteration 21, loss = 0.64692474
Iteration 22, loss = 0.64591550
Iteration 23, loss = 0.64491277
Iteration 24, loss = 0.64397057
Iteration 25, loss = 0.64302472
Iteration 26, loss = 0.64208743
Iteration 27, loss = 0.64112580
Iteration 28, loss = 0.64024631
Iteration 29, loss = 0.63931928
Iteration 30, loss = 0.63838705
Iteration 31, loss = 0.63745384
Iteration 32, los

C:\Users\NTX550\anaconda3\envs\mydeep\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(max_iter=1000, verbose=True)

In [9]:
model_mlp.predict( x_data )

array([0, 1, 1, 0])

In [10]:
model_mlp.score( x_data, y_data)

1.0

In [14]:
len( model_mlp.coefs_ )

2

In [16]:
model_mlp.coefs_[0].shape #2x100

(2, 100)

In [17]:
model_mlp.coefs_[1].shape #2x100

(100, 1)

In [18]:
len( model_mlp.intercepts_ )

2

In [19]:
model_mlp.intercepts_[0].shape

(100,)

In [20]:
model_mlp.intercepts_[1].shape

(1,)

In [21]:
model_mlp1 = MLPClassifier(hidden_layer_sizes=(100,50), verbose=True, max_iter=1000)
model_mlp1.fit( x_data, y_data)

Iteration 1, loss = 0.70257394
Iteration 2, loss = 0.69685089
Iteration 3, loss = 0.69239535
Iteration 4, loss = 0.68866967
Iteration 5, loss = 0.68528766
Iteration 6, loss = 0.68188143
Iteration 7, loss = 0.67868238
Iteration 8, loss = 0.67565706
Iteration 9, loss = 0.67280374
Iteration 10, loss = 0.67010855
Iteration 11, loss = 0.66738617
Iteration 12, loss = 0.66505729
Iteration 13, loss = 0.66265992
Iteration 14, loss = 0.66030924
Iteration 15, loss = 0.65764753
Iteration 16, loss = 0.65496353
Iteration 17, loss = 0.65233110
Iteration 18, loss = 0.64954268
Iteration 19, loss = 0.64665664
Iteration 20, loss = 0.64358614
Iteration 21, loss = 0.64065531
Iteration 22, loss = 0.63772453
Iteration 23, loss = 0.63462060
Iteration 24, loss = 0.63195433
Iteration 25, loss = 0.62929244
Iteration 26, loss = 0.62640387
Iteration 27, loss = 0.62331714
Iteration 28, loss = 0.62011975
Iteration 29, loss = 0.61674823
Iteration 30, loss = 0.61335896
Iteration 31, loss = 0.61008873
Iteration 32, los

C:\Users\NTX550\anaconda3\envs\mydeep\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, verbose=True)

In [23]:
len( model_mlp1.coefs_ )

3

In [25]:
model_mlp1.coefs_[0].shape #

(2, 100)

In [26]:
model_mlp1.coefs_[1].shape 

(100, 50)

In [27]:
model_mlp1.coefs_[2].shape 

(50, 1)

In [28]:
model_mlp1.predict( x_data) #4x2 2x100 = 4x100 100x50 = 4x50 50x1 => 4x1

array([0, 1, 1, 0])

In [ ]:
model_mlp2 = MLPClassifier(hidden_layer_sizes=(100,50,20), 
                           verbose=True, max_iter=1000)
model_mlp2.fit( x_data, y_data)

In [ ]:
# 2x100 100x50 50x20 20x1