In [30]:
import numpy as np
import pandas as pd

In [3]:
a = [i*100 for i in range(10)]
a

[0, 100, 200, 300, 400, 500, 600, 700, 800, 900]

In [4]:
a_arr = np.array(a)
a_arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [5]:
a_arr+10

array([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [8]:
# case 2)
x = [1, 2, 3, 4, 5]
y = [10, 20, 30, 40, 50]

In [9]:
test_arr = np.array(x)

In [10]:
test_arr.dtype

dtype('int32')

In [11]:
test_arr.ndim

1

In [15]:
test_arr = np.array([
                    [1,2,3,4,5],
                    [9,8,7,6,5],
                    [2,4,6,8,9]
                    ])
test_arr

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5],
       [2, 4, 6, 8, 9]])

In [16]:
test_arr[0][1]

2

In [17]:
test_arr.ndim

2

In [18]:
np.arange(0, 6, 1)

array([0, 1, 2, 3, 4, 5])

In [19]:
np.arange(0, 51, 10)

array([ 0, 10, 20, 30, 40, 50])

In [20]:
np.arange(0, 51, 10)[:, np.newaxis] + np.arange(0, 6, 1)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [24]:
a = np.arange(0, 51, 10)[:, np.newaxis] + np.arange(0, 6, 1)

In [25]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [28]:
a[0][3:5]

array([3, 4])

In [36]:
# 주식가격 리스트를 pandas series로 만들기.
stock_price_list = [10000,10300,9900,10500,11000]
stock_price_array = np.array(stock_price_list)
stock_price_series = pd.Series(stock_price_list)

print(stock_price_list)
print(stock_price_array)
print(stock_price_series)

[10000, 10300, 9900, 10500, 11000]
[10000 10300  9900 10500 11000]
0    10000
1    10300
2     9900
3    10500
4    11000
dtype: int64


In [37]:
stock_price_Series_index = pd.Series(stock_price_list,
                                    index=["2022-10-01",
                                           "2022-10-02",
                                           "2022-10-03",
                                           "2022-10-04",
                                           "2022-10-5"])

In [38]:
stock_price_Series_index

2022-10-01    10000
2022-10-02    10300
2022-10-03     9900
2022-10-04    10500
2022-10-5     11000
dtype: int64

In [ ]:
#  참고) 파이썬의 기본 자료형인 dict와 상당히 유사
# dict : key      ---  pandas : index
# 

In [42]:
s_data = {"APPL":1000, "MS":2000, "AMAZON":3000}
s_data_Series = pd.Series(s_data)
s_data_Series

APPL      1000
MS        2000
AMAZON    3000
dtype: int64

In [41]:
# pandas는 index 가 상당히 특징
# ----> 대부분의 움직임이 index를 중심으로 움직이게 된다
# 기준 : index
ticker = ["GOOGLE", "APPL", "AMAZON"]
s_data_Series2 = pd.Series(s_data, index = ticker)
s_data_Series2

GOOGLE       NaN
APPL      1000.0
AMAZON    3000.0
dtype: float64

In [44]:
temp = s_data_Series + s_data_Series2
temp

AMAZON    6000.0
APPL      2000.0
GOOGLE       NaN
MS           NaN
dtype: float64

In [45]:
temp.isnull()

AMAZON    False
APPL      False
GOOGLE     True
MS         True
dtype: bool

In [46]:
temp.notnull()

AMAZON     True
APPL       True
GOOGLE    False
MS        False
dtype: bool

In [48]:
temp[temp.isnull()]

GOOGLE   NaN
MS       NaN
dtype: float64

In [47]:
temp[temp.notnull()]

AMAZON    6000.0
APPL      2000.0
dtype: float64

In [49]:
temp.shape

(4,)

In [51]:
temp.dtype

dtype('float64')